[font]
size = 12.0

[font.normal]
family = "Fira Code"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[window.dimensions]
columns =  80
lines = 30
